/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/S9uP2Kuxzmv
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function UploadAudioForm() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900">
      <h1 className="text-3xl font-bold text-gray-800 dark:text-gray-200 mb-4">
        Cloned Audio Detector
      </h1>
      <p className="text-gray-600 dark:text-gray-400 mb-8">
        Upload WAV files to detect cloned audio
      </p>
      <div className="w-full max-w-md">
        <form className="space-y-4">
          <div className="space-y-2 relative group">
            <Label htmlFor="directory">Directory</Label>
            <Input accept=".wav" id="directory" multiple type="file" />
            <div className="absolute right-0 top-0 mt-2 mr-2 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 cursor-pointer">
              <svg
                className="w-6 h-6"
                fill="none"
                stroke="currentColor"
                viewBox="0 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M10 6H6a2 2 0 00-2 2v10a2 002 2h12a2 002-2V8a2 00-2-2h-4m-2 4l6 6m0-6L8 16"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                />
              </svg>
              <div className="opacity-0 group-hover:opacity-100 transition-opacity duration-200 absolute right-0 bg-white dark:bg-gray-800 text-gray-500 dark:text-gray-300 text-xs max-w-md p-2 mt-8 rounded shadow-lg border border-gray-200 dark:border-gray-700 dark:border-gray-800">
                <h2 className="font-bold mb-1">WAV File Requirements:</h2>
                <ul className="list-disc list-inside space-y-1">
                  <li>Only WAV files are accepted.</li>
                  <li>Each file should be 3-5 seconds long.</li>
                  <li>Files must have a 16KHz sampling rate.</li>
                  <li>Maximum of 20 files can be uploaded.</li>``
                </ul>
              </div>
            </div>
          </div>
          <Button className="w-full" type="submit">
            Detect
          </Button>
        </form>
        <div className="mt-8 w-full max-w-md">
          <h2 className="text-lg font-bold text-gray-800 dark:text-gray-200 mb-4">
            Uploaded Files:
          </h2>
          <div className="space-y-4">
            <div className="flex items-center justify-between bg-gray-200 dark:bg-gray-800 p-2 rounded">
              <span className="text-gray-800 dark:text-gray-200">
                file1.wav
              </span>
              <div className="flex items-center space-x-2">
                <div className="w-32 bg-white dark:bg-gray-700 rounded">
                  <div
                    className="h-2 bg-green-500 rounded"
                    style={{
                      width: "70%",
                    }}
                  />
                </div>
                <svg
                  className="w-6 h-6 text-green-500"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M5 13l4 4L19 7"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                  />
                </svg>
              </div>
            </div>
            <div className="flex items-center justify-between bg-gray-200 dark:bg-gray-800 p-2 rounded">
              <span className="text-gray-800 dark:text-gray-200">
                file2.wav
              </span>
              <div className="flex items-center space-x-2">
                <div className="w-32 bg-white dark:bg-gray-700 rounded">
                  <div
                    className="h-2 bg-red-500 rounded"
                    style={{
                      width: "100%",
                    }}
                  />
                </div>
                <svg
                  className="w-6 h-6 text-red-500"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M6 18L18 6M6 6l12 12"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                  />
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
